// <auto-generated />
using EmmasBlogg.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace EmmasBlogg.Migrations
{
    [DbContext(typeof(InläggsContext))]
    partial class InläggsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmmasBlogg.Models.Användare", b =>
                {
                    b.Property<int>("AnvändarID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Efternamn");

                    b.Property<string>("Epostadress");

                    b.Property<string>("Namn");

                    b.HasKey("AnvändarID")
                        .HasName("PK_AnvändarID");

                    b.ToTable("Användare");
                });

            modelBuilder.Entity("EmmasBlogg.Models.Inlägg", b =>
                {
                    b.Property<int>("InläggsID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnvändareAnvändarID");

                    b.Property<DateTime>("Datum");

                    b.Property<int?>("KategoriID");

                    b.Property<string>("Text");

                    b.Property<string>("Titel");

                    b.HasKey("InläggsID")
                        .HasName("PK_InläggsID");

                    b.HasIndex("AnvändareAnvändarID");

                    b.HasIndex("KategoriID");

                    b.ToTable("Poster");
                });

            modelBuilder.Entity("EmmasBlogg.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Namn");

                    b.HasKey("KategoriID")
                        .HasName("PK_KategoriID");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("EmmasBlogg.Models.Inlägg", b =>
                {
                    b.HasOne("EmmasBlogg.Models.Användare", "Användare")
                        .WithMany()
                        .HasForeignKey("AnvändareAnvändarID");

                    b.HasOne("EmmasBlogg.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriID");
                });
#pragma warning restore 612, 618
        }
    }
}
